logbook:
  exclude:
    - /actuator/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  write:
    chunk-size: 1000
    level: debug
    max-body-size: -1
